spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/source
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console.enabled: true

#liquibase change log file

liquibase:
  enabled: false
